language: php
#
# Required test environments.
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
env:
  - TRAVISCI_PHPUNIT_VERSION=':4.8.24'
  - TRAVISCI_PHPUNIT_VERSION=':5.7'
matrix:
  exclude:
    - php: '5.5'
      env: TRAVISCI_PHPUNIT_VERSION=':5.7'
    - php: '5.6'
      env: TRAVISCI_PHPUNIT_VERSION=':4.8.24'
    - php: '7.1'
      env: TRAVISCI_PHPUNIT_VERSION=':4.8.24'
    - php: '7.0'
      env: TRAVISCI_PHPUNIT_VERSION=':4.8.24'
    - php: nightly
      env: TRAVISCI_PHPUNIT_VERSION=':4.8.24'
  allow_failures:
    - php: nightly
    - php: '7.1'
#
# Notifications.
notifications:
  irc: "irc.freenode.org#TooBasic"
#
# Pre-installation steps.
before_install:
  - composer require "phpunit/phpunit${TRAVISCI_PHPUNIT_VERSION}"

script:
  - ./vendor/phpunit/phpunit/phpunit --configuration phpunit.xml
